[package]
name = "unsplash-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
cacao = "0.3.2"
indicatif = "0.17.11"
ureq = {  version = "3.0.6", features = ["json"] }
serde = { version = "1", features = ["derive"] }
config = "0.15.8"
dotenv = "0.15.0"
rand = "0.9.0"
